<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        // Drop existing foreign key to allow altering the column
        Schema::table('visits', function (Blueprint $table) {
            // The default foreign key name generated by Laravel
            $table->dropForeign(['department_id']);
        });

        // Make department_id nullable without requiring doctrine/dbal
        DB::statement('ALTER TABLE `visits` MODIFY `department_id` BIGINT UNSIGNED NULL');

        // Recreate foreign key with ON DELETE SET NULL
        Schema::table('visits', function (Blueprint $table) {
            $table->foreign('department_id')
                ->references('id')
                ->on('departments')
                ->nullOnDelete();
        });
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        // WARNING: Reverting to NOT NULL may fail if rows contain NULLs.
        // Proceed by restoring the previous constraint and not-null setting.

        Schema::table('visits', function (Blueprint $table) {
            $table->dropForeign(['department_id']);
        });

        DB::statement('ALTER TABLE `visits` MODIFY `department_id` BIGINT UNSIGNED NOT NULL');

        Schema::table('visits', function (Blueprint $table) {
            $table->foreign('department_id')
                ->references('id')
                ->on('departments')
                ->onDelete('cascade');
        });
    }
};
